# Configuration de l'image Docker
shiny:
  image:
    repository: VOTRE_USERNAME_DOCKERHUB/consultation-bte-app
    tag: latest
    pullPolicy: Always

  # Configuration de l'Ingress (URL d'accès)
  ingress:
    enabled: true
    hostname: "consultation-bte.lab.sspcloud.fr"
    tls: true

  # Ressources allouées
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 512Mi

  # Stockage S3/MinIO (si vous utilisez MinIO)
  s3:
    enabled: false  # Mettez true si vous voulez utiliser MinIO
    existingSecret: "consultation-bte-s3"

  # Base de données PostgreSQL (si nécessaire)
  postgresql:
    enabled: false  # Mettez true si vous voulez une base de données
    username: consultation
    database: consultation_db
    fullnameOverride: consultation-postgresql
    existingSecret: "consultation-bte-postgresql"

  # Réplicats (nombre d'instances)
  replicaCount: 1

  # Variable d'environnement pour le mot de passe admin
  env:
    - name: ADMIN_PASSWORD
      value: "ChangezMoiEnProduction12!"